name: Drone News V2 — Brief & Insights

on:
  workflow_dispatch:
  schedule:
    # 09:00 America/New_York (13:00 UTC) daily
    - cron: "0 13 * * *"
  push:
    paths:
      - "data/**/*.json"

permissions:
  contents: write

jobs:
  brief:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # Optional: override model (default set in script)
      # OPENAI_MODEL: o4-mini
      DATA_DIR: data
      OUT_DIR: reports
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai==1.* orjson python-dateutil

      - name: Generate brief
        run: |
          python .github/scripts/drone_v2_report.py \
            --data-dir "${DATA_DIR}" \
            --out-dir "${OUT_DIR}" \
            --window-hours 36 \
            --system-prompt "prompts/system_drone_analyst.md"

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: daily drone brief $(date -u +%Y-%m-%d)"
            git push
          fi
